"""
Automatically translated from C++ to Python

Original file: calculator.cpp
Module: calculator

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

Sure, I can help with that. However, you didn't provide the C++ code that needs to be translated. Could you please provide the C++ code?