"""
Automatically translated from C++ to Python

Original file: utils.cpp
Module: utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

In order to provide a translation, I would need the actual C++ code that needs to be translated to Python. The information provided does not include any C++ code. Could you please provide the C++ code that needs to be translated?