"""
Automatically translated from C++ to Python

Original file: utils.h
Module: utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

As an AI, I need the actual C++ code to be translated into Python. Please provide the C++ code you want to convert to Python.